[package]
name = "qwikboot"
version = "0.1.3"
edition = "2024"

[dependencies]
chrono = "0.4.41"
console = "0.16.0"
dialoguer = "0.12.0"
reqwest = { version = "0.11", features = ["blocking"] }
tempfile = "3.21.0"
tokio = { version = "1.0", features = ["full"] }
