name: Release

on:
  push:
    tags:
      - 'v*'
      
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "macos-latest", "windows-latest"]
            include:
            - os: ubuntu-latest
              target: x86_64-unknown-linux-gnu
            - os: macos-latest
              target: x86_64-apple-darwin
            - os: windows-latest
              target: x86_64-pc-windows-gnu

    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            target: ${{ matrix.target }}

        - name: Build Release Binaries
          run: cargo build --release --target ${{ matrix.target }}

        - name: Package Binaries
          shell: bash
          run: |
            mkdir dist
            if [ "${{ matrix.target }}" = "x86_64-pc-windows-gnu" ]; then
              cp target/${{ matrix.target }}/release/qwikboot.exe dist/
              cd dist && zip qwikboot-${{ matrix.target }}.zip qwikboot.exe
            else
              cp target/${{ matrix.target }}/release/qwikboot dist/
              cd dist && tar -czf qwikboot-${{ matrix.target }}.tar.gz qwikboot
            fi
        - name: Upload Binaries to GitHub Releases
          uses: softprops/action-gh-release@v2
          with:
            files: dist/*
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}